{
 "title": "Horus - Dashboard",
 "tags": [ "sap" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "PROJECT",
    "label": "PROJECT",
    "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(bucket: \"horus\", tag: \"project\")\n"
   },
   {
    "name": "SID",
    "query": "import \"influxdata/influxdb/schema\"\nimport \"strings\"\nschema.tagValues(bucket: \"horus\", tag: \"sap_sid\")\n"
   },
   {
    "name": "INSTANCE_ID",
    "label": "INSTANCE_ID",
    "query": "from(bucket: \"horus\")\n|> range(start: v.timeRangeStart)\n|> filter(fn:(r) => r._measurement == \"monitoring\" and  r[\"project\"] == \"${PROJECT}\")\n|> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n|> group()\n|> distinct(column: \"instance_id\")\n"
   }
  ]
 },
 "panels": [
  { "title": "Global Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ABAP - Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"horus\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"monitoring\")\n  |> filter(fn: (r) => r[\"product_type\"] == \"abap\")\n  |> filter(fn: (r) => if \"${PROJECT}\" == \"ALL\" then r[\"project\"] =~/$/ else  r[\"project\"] == \"${PROJECT}\")\n  |> last()\n  |> filter(fn: (r) => r[\"_field\"] == \"abap_isup\" and r._value == 0)\n  |> group()\n"
    }
   ]
  },
  {
   "title": "SITE - Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"horus\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"monitoring\" and r[\"_field\"] == \"site_isup\")\n  |> filter(fn: (r) => if \"${PROJECT}\" == \"ALL\" then r[\"project\"] =~/$/ else  r[\"project\"] == \"${PROJECT}\")\n  |> last()\n  |> filter(fn: (r) => r[\"_field\"] == \"site_isup\" and r._value == 0)\n  |> group()\n"
    }
   ]
  },
  {
   "title": "BACKUP - status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"horus\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"monitoring\")\n  |> filter(fn: (r) => r[\"backup\"] == \"backup\")\n  |> filter(fn: (r) => r[\"sap_sid\"] == \"HPL\")\n  |> filter(fn: (r) => r[\"_field\"] == \"backup_status\")\n  |> last()\n  |> group()\n\n"
    }
   ]
  },
  {
   "title": "System Overview - ABAP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "SAP - Status",
     "type": "status-history",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"horus\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"monitoring\")\n  |> filter(fn: (r) => r[\"_field\"] == \"abap_isup\")\n  |> filter(fn: (r) => r[\"instance_id\"] == \"${INSTANCE_ID}\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "SAP - Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "query": "from(bucket: \"horus\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"monitoring\")\n  |> filter(fn: (r) => r[\"_field\"] == \"sap_memory_total\" or r[\"_field\"] == \"sap_memory_used\")\n  |> filter(fn: (r) => r[\"instance_id\"] == \"${INSTANCE_ID}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "SAP - Dialog",
     "type": "bargauge",
     "gridPos": { "h": 2, "w": 10, "x": 12, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "query": "from(bucket: \"horus\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"sap_wp_info\"] == \"sap_wp_info\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wp_dia_running\" or r[\"_field\"] == \"wp_dia_total\")\n  |> filter(fn: (r) => r[\"instance_id\"] == \"${INSTANCE_ID}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\n  |> last()"
      }
     ]
    },
    {
     "title": "Stuck Jobs",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"horus\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"monitoring\")\n  |> filter(fn: (r) => r[\"_field\"] == \"abap_stuck_jobs\")\n  |> filter(fn: (r) => r[\"instance_id\"] == \"${INSTANCE_ID}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "SAP - Background",
     "type": "bargauge",
     "gridPos": { "h": 2, "w": 10, "x": 12, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "query": "from(bucket: \"horus\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"sap_wp_info\"] == \"sap_wp_info\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wp_bgd_running\" or r[\"_field\"] == \"wp_bgd_total\")\n  |> filter(fn: (r) => r[\"instance_id\"] == \"${INSTANCE_ID}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\n  |> last()"
      }
     ]
    },
    {
     "title": "SAP - Spool",
     "type": "bargauge",
     "gridPos": { "h": 2, "w": 10, "x": 12, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "query": "from(bucket: \"horus\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"sap_wp_info\"] == \"sap_wp_info\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wp_spo_running\" or r[\"_field\"] == \"wp_spo_total\")\n  |> filter(fn: (r) => r[\"instance_id\"] == \"${INSTANCE_ID}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\n  |> last()"
      }
     ]
    },
    {
     "title": "SAP - Update",
     "type": "bargauge",
     "gridPos": { "h": 2, "w": 10, "x": 12, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "query": "from(bucket: \"horus\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"sap_wp_info\"] == \"sap_wp_info\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wp_upd_running\" or r[\"_field\"] == \"wp_upd_total\")\n  |> filter(fn: (r) => r[\"instance_id\"] == \"${INSTANCE_ID}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\n  |> last()"
      }
     ]
    },
    {
     "title": "SAP - Response Times",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "  from(bucket: \"horus\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"monitoring\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rtime_background\" or r[\"_field\"]  == \"rtime_dialog\" or r[\"_field\"] == \"rtime_http\" or r[\"_field\"] == \"rtime_https\" or r[\"_field\"] == \"rtime_rfc\")\n  |> filter(fn: (r) => r[\"_value\"] > 0)\n  |> filter(fn: (r) => r[\"instance_id\"] == \"${INSTANCE_ID}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "SAP - Buffers Hitratio",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 10, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"horus\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"buffer_hitratio\")\n  |> filter(fn: (r) => r[\"instance_id\"] == \"${INSTANCE_ID}\")\n  |> last()"
      }
     ]
    }
   ]
  },
  {
   "title": "System Overview - Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    { "title": "Hana - Memory", "type": "timeseries", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 } },
    {
     "title": "HANA - Alerts",
     "type": "table",
     "gridPos": { "h": 8, "w": 10, "x": 12, "y": 3 },
     "targets": [
      {
       "query": "from(bucket: \"horus\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"alerts\")\n  |> filter(fn: (r) => r[\"hana\"] == \"hana\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ALERT_NAME\" or r[\"_field\"] == \"ALERT_RATING\")\n"
      }
     ]
    },
    {
     "title": "Last Backup",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"horus\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"monitoring\")\n  |> filter(fn: (r) => r[\"instance_id\"] == \"${INSTANCE_ID}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"isupdate\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Security - ABAP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hardening - Parameters",
     "type": "table",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
     "targets": [
      {
       "query": "\nfrom(bucket: \"horus\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"security\")\n  |> filter(fn: (r) => r[\"hardening\"] == \"hardening\")\n  |> filter(fn: (r) => r[\"abap_parameters\"] == \"abap_parameters\")    \n  |> filter(fn: (r) => r[\"instance_id\"] == \"${INSTANCE_ID}\")\n  |> last()\n  |> group(columns: [\"sap_sid\"])\n  |> keep(columns: [\"_value\", \"_field\"])\n"
      }
     ]
    },
    {
     "title": "Hardening - Protocols",
     "type": "table",
     "gridPos": { "h": 8, "w": 7, "x": 6, "y": 20 },
     "targets": [
      {
       "query": "\nfrom(bucket: \"horus\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"security\")\n  |> filter(fn: (r) => r[\"hardening\"] == \"hardening\")\n  |> filter(fn: (r) => r[\"icm_info\"] == \"icm_info\")\n  |> filter(fn: (r) => r[\"instance_id\"] == \"${INSTANCE_ID}\")\n  |> toString()\n  |> group(columns: [\"_field\"])\n  |> keep(columns: [\"_value\", \"_field\"])\n"
      }
     ]
    },
    {
     "title": "Hardening - Ports",
     "type": "table",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 20 },
     "targets": [
      {}
     ]
    }
   ]
  },
  {
   "title": "Alerting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    { "title": "SAP - Alerts", "type": "alertlist", "gridPos": { "h": 15, "w": 24, "x": 0, "y": 21 } }
   ]
  },
  {
   "title": "System Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "query": "from(bucket: \"horus\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"monitoring\" and r._field == \"wp_dia_running\")\n    |> group(columns: [\"sap_sid\"])\n    |> last()\n    |> group()\n    |> keep(columns: [\"_value\", \"sap_sid\"])\n"
      },
      {
       "query": "from(bucket: \"horus\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"monitoring\" and r._field == \"wp_bgd_running\")\n    |> group(columns: [\"sap_sid\"])\n    |> last()\n    |> group()\n    |> keep(columns: [\"_value\", \"sap_sid\"])"
      },
      {
       "query": "from(bucket: \"horus\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"monitoring\" and r._field == \"wp_upd_running\")\n    |> group(columns: [\"sap_sid\"])\n    |> last()\n    |> group()\n    |> keep(columns: [\"_value\", \"sap_sid\"])"
      },
      {
       "query": "from(bucket: \"horus\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"monitoring\" and r._field == \"wp_spo_running\")\n    |> group(columns: [\"sap_sid\"])\n    |> last()\n    |> group()\n    |> keep(columns: [\"_value\", \"sap_sid\"])"
      }
     ]
    }
   ]
  },
  {
   "title": "TESTS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "SAP - Workprocess",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 11, "x": 0, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"horus\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"sap_wp_info\"] == \"sap_wp_info\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wp_dia_running\" or r[\"_field\"] == \"wp_dia_total\" or r[\"_field\"] == \"wp_bgd_running\" or r[\"_field\"] == \"wp_bgd_total\" or r[\"_field\"] == \"wp_upd_running\" or r[\"_field\"] == \"wp_upd_total\" or r[\"_field\"] == \"wp_spo_running\" or r[\"_field\"] == \"wp_spo_total\")\n  |> filter(fn: (r) => r[\"sap_sid\"] == \"${SID}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Dumps",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 18, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"horus\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"monitoring\")\n  |> filter(fn: (r) => r[\"instance_id\"] == \"${INSTANCE_ID}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"isupdate\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Priv. mode",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"horus\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"monitoring\")\n  |> filter(fn: (r) => r[\"instance_id\"] == \"${INSTANCE_ID}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"isupdate\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "SITE - Status",
     "type": "state-timeline",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "query": "from(bucket: \"horus\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"monitoring\")\n  |> drop(columns: [\"column\", \"url\"])\n  |> filter(fn: (r) => r[\"_field\"] == \"site_isup\")\n  |> aggregateWindow(every: 10m, fn: mean, createEmpty: false)\n"
      }
     ]
    },
    {
     "title": "ABAP - Status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"horus\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"monitoring\")\n  |> filter(fn: (r) => r[\"product_type\"] == \"abap\")\n  |> last()\n  |> filter(fn: (r) => r[\"_field\"] == \"abap_isup\" and r._value == 0)\n"
      }
     ]
    },
    {
     "title": "SITE - Status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"horus\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"monitoring\")\n  |> drop(columns: [\"column\", \"url\"])\n  |> last()  \n  |> filter(fn: (r) => r[\"_field\"] == \"site_isup\" and r._value == 0)\n\n"
      }
     ]
    },
    {
     "title": "SAP - Memory",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"horus\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"monitoring\")\n  |> filter(fn: (r) => r[\"_field\"] == \"sap_memory_total\" or r[\"_field\"] == \"sap_memory_used\")\n  |> filter(fn: (r) => r[\"sap_sid\"] == \"${SID}\")\n"
      }
     ]
    },
    {
     "title": "http",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 31 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"horus\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"monitoring\")\n  |> filter(fn: (r) => r[\"_field\"] == \"http\")\n  |> filter(fn: (r) => r[\"sid\"] == \"${SID}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "SAP - Buffers Hitratio",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"horus\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"buffer_hitratio\")\n  |> filter(fn: (r) => r[\"sap_sid\"] == \"${SID}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")"
      }
     ]
    }
   ]
  }
 ]
}